language: java

dist: trusty

git:
  depth: false

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script: ci/script.sh

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    draft: true
    on:
      tags: true
